# Generated by Django 4.2.6 on 2023-11-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_location_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sickinfomodel',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
