# Generated by Django 4.2.6 on 2023-11-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sickinfomodel_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalregistrationmodel',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalregistrationmodel',
            name='region',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalregistrationmodel',
            name='street',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='hospitalregistrationmodel',
            name='ward',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
