# Generated by Django 4.2.6 on 2023-11-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hospitalregistrationmodel_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalregistrationmodel',
            name='registerd_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
