# Generated by Django 4.2.6 on 2023-11-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_hospitalregistrationmodel_registerd_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalregistrationmodel',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
