# Generated by Django 4.2.6 on 2023-11-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_hospitalservices_sickinfomodel_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalregistrationmodel',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.hospitalservices'),
        ),
    ]
