# Generated by Django 4.2.6 on 2023-11-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hospitalregistrationmodel_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sickinfomodel',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='hospitalregistrationmodel',
            name='service',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sickinfomodel',
            name='service',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='HospitalServices',
        ),
    ]
